annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 240711.0.0
dependencies:
- name: common
  version: 23.0.10
  repository: oci://tccr.io/truecharts
  condition: ""
  alias: ""
  tags: []
  import-values: []
- condition: mariadb.enabled
  name: mariadb
  repository: oci://tccr.io/truecharts
  version: 14.0.10
description: PhotoPrism® is a server-based application for browsing, organizing and
  sharing your personal photo collection
home: https://truecharts.org/charts/stable/photoprism
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoprism.webp
keywords:
- photos
- photoprism
- pictures
- sharing
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: photoprism
sources:
- https://github.com/photoprism/photoprism
- https://github.com/truecharts/charts/tree/master/charts/stable/photoprism
- https://hub.docker.com/r/photoprism/photoprism
type: application
version: 23.4.0
