annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: GIT
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 1.22.1
dependencies:
- name: common
  repository: oci://tccr.io/truecharts
  version: 24.1.5
- condition: memcached.enabled
  name: memcached
  repository: oci://tccr.io/truecharts
  version: 14.1.5
description: Self hosted GIT repositories
home: https://truecharts.org/charts/stable/gitea
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gitea.webp
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gitea
sources:
- https://gitea.com/gitea/helm-chart
- https://github.com/go-gitea/gitea
- https://github.com/truecharts/charts/tree/master/charts/stable/gitea
- https://hub.docker.com/r/gitea/gitea
type: application
version: 20.3.1
