annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: oci://tccr.io/truecharts
  version: 24.1.6
- alias: cloudnative-pg
  name: cloudnative-pg
  repository: https://cloudnative-pg.github.io/charts
  version: 0.21.5
description: CloudNativePG is a clustered postgresql database operator
home: https://truecharts.org/charts/system/cloudnative-pg
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cloudnative-pg.webp
keywords:
- database
- cloudnative-pg
- cnpg
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cloudnative-pg
sources:
- https://cloudnative-pg.io/
- https://github.com/cloudnative-pg
- https://github.com/truecharts/charts/tree/master/charts/system/cloudnative-pg
- https://github.com/truecharts/containers/tree/master/apps/alpine
type: application
version: 8.1.1
