annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: oci://tccr.io/truecharts
  version: 24.1.6
- alias: metallb
  name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.14.5
description: A network load-balancer implementation for Kubernetes using standard
  routing protocols
home: https://truecharts.org/charts/system/metallb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/metallb.webp
keywords:
- metallb
- loadbalancer
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: metallb
sources:
- https://github.com/metallb/metallb
- https://github.com/truecharts/charts/tree/master/charts/system/metallb
- https://github.com/truecharts/containers/tree/master/apps/alpine
- https://metallb.universe.tf
type: application
version: 16.1.1
