name: "Apps: Test PR"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    container:
      image: ixsystems/catalog_validation:latest

    steps:
      - name: Install Helm
        run: curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mark directory as safe
        run: git config --global --add safe.directory /__w/truecharts-catalog/truecharts-catalog

      - name: Fetch base branch history
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/test-2:refs/remotes/origin/test-2

      - name: Setup catalog validation
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-all-dev python3-venv
          python3 -m venv venv
          source venv/bin/activate
          git clone https://github.com/truenas/catalog_validation
          pip install --upgrade pip
          pip install --disable-pip-version-check --exists-action w -r catalog_validation/requirements.txt
          pip install -U catalog_validation/.

      - name: Validate changed charts
        run: |
          source venv/bin/activate
          /bin/bash -c "PWD=${pwd}; sudo /usr/local/bin/charts_validate deploy --path $PWD"

      - name: Validate catalog format
        run: |
          source venv/bin/activate
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_validate validate --path $PWD"